# Generated by Django 5.0.1 on 2024-02-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('value', models.CharField(max_length=512)),
                ('kind', models.IntegerField(choices=[('JA3', 0), ('JA3N', 1), ('HTTP2', 2), ('JS', 3), ('CANVAS', 4), ('WEBGL', 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=32, null=True)),
                ('system', models.CharField(max_length=64)),
                ('kind', models.IntegerField(choices=[('HTTP_CLIENT', 1), ('BROWSER', 2), ('SEARCH_BOT', 3), ('MALWARE', 4)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fingerprints', models.ManyToManyField(to='backend.fingerprint')),
            ],
        ),
    ]
