# Generated by Django 5.0.1 on 2024-02-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprint',
            name='kind',
            field=models.IntegerField(choices=[(0, 'JA3'), (1, 'JA3N'), (2, 'HTTP2'), (3, 'JS'), (4, 'CANVAS'), (5, 'WEBGL')]),
        ),
        migrations.AlterField(
            model_name='tool',
            name='kind',
            field=models.IntegerField(choices=[(1, 'HTTP_CLIENT'), (2, 'BROWSER'), (3, 'SEARCH_BOT'), (4, 'MALWARE')]),
        ),
    ]
