# Generated by Django 4.2.9 on 2024-02-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_tool_fingerprints_alter_fingerprint_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprint',
            name='kind',
            field=models.IntegerField(choices=[(0, 'Ja3'), (1, 'Ja3N'), (2, 'Http2'), (3, 'Js'), (4, 'Canvas'), (5, 'Webgl')]),
        ),
    ]
