# Generated by Django 4.2.9 on 2024-02-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_fingerprint_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprint',
            name='state',
            field=models.IntegerField(choices=[(0, 'Trusted'), (3, 'Untrusted'), (9, 'Blacklisted')], default=3),
        ),
        migrations.AlterField(
            model_name='tool',
            name='kind',
            field=models.IntegerField(choices=[(1, 'Http Client'), (2, 'Browser'), (3, 'Search Bot'), (4, 'Malware')]),
        ),
    ]
