# Generated by Django 4.2.9 on 2024-02-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_fingerprint_state_alter_tool_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fingerprint',
            name='value',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
